// flow-typed signature: 56ddf48d067d19440669bc1abf3e24c4
// flow-typed version: <<STUB>>/typeface-roboto-mono_v0.0.54/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typeface-roboto-mono'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typeface-roboto-mono' {
  declare module.exports: any;
}
