// src/js/constants/action-types.js

export const ADD_ODM = "ADD_ODM";
export const ADD_STDCONST = "ADD_STDCONST";
export const ADD_STDCT = "ADD_STDCT";
export const UPD_ITEMGROUP = "UPD_ITEMGROUP";
export const ADD_ITEMGROUP = "ADD_ITEMGROUP";
export const ADD_ITEMGROUPCOMMENT = "ADD_ITEMGROUPCOMMENT";
export const UPD_ITEMGROUPCOMMENT = "UPD_ITEMGROUPCOMMENT";
export const DEL_ITEMGROUPCOMMENT = "DEL_ITEMGROUPCOMMENT";
export const UPD_ITEMDEF= "UPD_ITEMDEF";
export const UPD_ITEMREF= "UPD_ITEMREF";
export const UPD_ITEMREFKEYORDER= "UPD_ITEMREFKEYORDER";
export const UPD_ITEMCLDF = "UPD_ITEMCLDF";
export const UPD_ITEMDESCRIPTION = "UPD_ITEMDESCRIPTION";
export const ADD_VAR = "ADD_VAR";
export const DEL_VARS = "DEL_VARS";
export const ADD_CODELIST = "ADD_CODELIST";
export const UPD_CODELIST = "UPD_CODELIST";
export const DEL_CODELISTS = "DEL_CODELISTS";
export const UPD_CODELISTSTDOIDS = "UPD_CODELISTSTDOIDS";
export const UPD_CDVAL = "UPD_CDVAL";
